plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'org.asciidoctor.jvm.convert' version '4.0.5'
	id 'jacoco'
}

group = 'com.cubinghub'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

asciidoctorj {
	version = '3.0.1'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	asciidoctorExt
}

repositories {
	mavenCentral()
}

ext {
	set('snippetsDir', file("build/generated-snippets"))
}

def jacocoExcludes = [
	'**/domain/**/entity/Q*.class',
	'**/common/Q*.class',
	'**/config/SecurityConfig.class',
	'**/CubingHubApplication.class'
]

dependencies {
	implementation platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
	developmentOnly platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
	annotationProcessor platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
	testImplementation platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
	testAnnotationProcessor platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
	asciidoctorExt platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)

	// 1. web
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'

	// 2. security & JWT
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

	// 3. DB (JPA, MySQL, QueryDSL)
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-flyway'
	implementation 'org.flywaydb:flyway-mysql'
	runtimeOnly 'com.mysql:mysql-connector-j'
	implementation 'com.querydsl:querydsl-jpa::jakarta'
	annotationProcessor 'com.querydsl:querydsl-apt::jakarta'
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"

	// 4. 캐시 & 세션
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// 5. 모니터링
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

	// 6. Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// 7. 테스트 (JUnit, Security)
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-redis-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-restdocs'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// 8. 테스트 컨테이너
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
	testImplementation 'org.testcontainers:testcontainers-mysql'
	testImplementation 'com.redis:testcontainers-redis'

	// 9. Rest Docs
	asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
}

tasks.named('test') {
	outputs.dir snippetsDir
	useJUnitPlatform()
}

tasks.named('jacocoTestReport') {
	dependsOn test
	classDirectories.setFrom(
			files(sourceSets.main.output.classesDirs.asFileTree.matching {
				exclude jacocoExcludes
			})
	)
	reports {
		xml.required = true
		html.required = true
		csv.required = false
	}
}

// copyDocument 태스크와의 충돌을 방지하기 위해 리소스 처리 시 static/docs 폴더를 제외
tasks.named('processResources') {
	exclude('static/docs/**')
}

tasks.named('asciidoctor') {
	inputs.dir snippetsDir
	configurations 'asciidoctorExt'
	dependsOn test
}

tasks.register('copyDocument', Copy) {
	dependsOn asciidoctor
	from file("build/docs/asciidoc")
	into file("src/main/resources/static/docs")
}

bootJar {
	dependsOn asciidoctor
	from ("${asciidoctor.outputDir}") {
		into 'static/docs'
	}
}

tasks.named('bootRun') {
	dependsOn asciidoctor
}

tasks.named('build') {
	dependsOn copyDocument
}
