services:
  db-admin-proxy:
    image: alpine/socat:1.8.0.3
    profiles:
      - admin
    command:
      - TCP-LISTEN:3307,fork,reuseaddr
      - TCP:db:3306
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 127.0.0.1:3307:3307
    networks:
      - application
