// Auto-generated by script
export const mockLearningTabs = [
  { key: 'F2L', label: 'F2L', itemCount: 41 },
  { key: 'OLL', label: 'OLL', itemCount: 57 },
  { key: 'PLL', label: 'PLL', itemCount: 21 },
];

export const mockLearningCases = {
  F2L: [
    {
        "id": "f2l-01",
        "name": "F2L 01",
        "algorithm": "U R U' R'"
    },
    {
        "id": "f2l-02",
        "name": "F2L 02",
        "algorithm": "U' F' U F"
    },
    {
        "id": "f2l-03",
        "name": "F2L 03",
        "algorithm": "R U R' U' R U R'"
    },
    {
        "id": "f2l-04",
        "name": "F2L 04",
        "algorithm": "F' U' F U F' U' F"
    },
    {
        "id": "f2l-05",
        "name": "F2L 05",
        "algorithm": "U' R U R' U2 R U' R'"
    },
    {
        "id": "f2l-06",
        "name": "F2L 06",
        "algorithm": "d R' U' R U2 R' U R"
    },
    {
        "id": "f2l-07",
        "name": "F2L 07",
        "algorithm": "U' R U R' U R U R'"
    },
    {
        "id": "f2l-08",
        "name": "F2L 08",
        "algorithm": "U F' U' F U' F' U' F"
    },
    {
        "id": "f2l-09",
        "name": "F2L 09",
        "algorithm": "U' R U' R' U F' U' F"
    },
    {
        "id": "f2l-10",
        "name": "F2L 10",
        "algorithm": "U R U R' U' R U' R'"
    },
    {
        "id": "f2l-11",
        "name": "F2L 11",
        "algorithm": "R U R' U2 R U R'"
    },
    {
        "id": "f2l-12",
        "name": "F2L 12",
        "algorithm": "F' U' F U2 F' U' F"
    },
    {
        "id": "f2l-13",
        "name": "F2L 13",
        "algorithm": "y' U R U' R' U R U' R'"
    },
    {
        "id": "f2l-14",
        "name": "F2L 14",
        "algorithm": "U' R U R' U y' R' U' R"
    },
    {
        "id": "f2l-15",
        "name": "F2L 15",
        "algorithm": "R U' R' U R U' R'"
    },
    {
        "id": "f2l-16",
        "name": "F2L 16",
        "algorithm": "F' U F U' F' U F"
    },
    {
        "id": "f2l-17",
        "name": "F2L 17",
        "algorithm": "U R U2 R' U R U' R'"
    },
    {
        "id": "f2l-18",
        "name": "F2L 18",
        "algorithm": "y' U' R' U2 R U' R' U R"
    },
    {
        "id": "f2l-19",
        "name": "F2L 19",
        "algorithm": "U R U' R' U R U' R'"
    },
    {
        "id": "f2l-20",
        "name": "F2L 20",
        "algorithm": "y' U' R' U R U' R' U R"
    },
    {
        "id": "f2l-21",
        "name": "F2L 21",
        "algorithm": "R U' R' U2 R U R'"
    },
    {
        "id": "f2l-22",
        "name": "F2L 22",
        "algorithm": "F' U F U2 F' U' F"
    },
    {
        "id": "f2l-23",
        "name": "F2L 23",
        "algorithm": "U2 R U R' U R U' R'"
    },
    {
        "id": "f2l-24",
        "name": "F2L 24",
        "algorithm": "y' U2 R' U' R U' R' U R"
    },
    {
        "id": "f2l-25",
        "name": "F2L 25",
        "algorithm": "y' U R' U' R U' R' U' R"
    },
    {
        "id": "f2l-26",
        "name": "F2L 26",
        "algorithm": "U' R U R' U R U R'"
    },
    {
        "id": "f2l-27",
        "name": "F2L 27",
        "algorithm": "R U' R' U R U' R' U R U' R'"
    },
    {
        "id": "f2l-28",
        "name": "F2L 28",
        "algorithm": "y' R' U R U' R' U R U' R' U R"
    },
    {
        "id": "f2l-29",
        "name": "F2L 29",
        "algorithm": "y' R' U' R U R' U' R"
    },
    {
        "id": "f2l-30",
        "name": "F2L 30",
        "algorithm": "R U R' U' R U R'"
    },
    {
        "id": "f2l-31",
        "name": "F2L 31",
        "algorithm": "U' R U' R' U2 R U' R'"
    },
    {
        "id": "f2l-32",
        "name": "F2L 32",
        "algorithm": "y' U R' U R U2 R' U R"
    },
    {
        "id": "f2l-33",
        "name": "F2L 33",
        "algorithm": "U' R U R' U2 R U R'"
    },
    {
        "id": "f2l-34",
        "name": "F2L 34",
        "algorithm": "U R U' R' U2 F' U' F"
    },
    {
        "id": "f2l-35",
        "name": "F2L 35",
        "algorithm": "U' R U' R' U R U R' U R U' R'"
    },
    {
        "id": "f2l-36",
        "name": "F2L 36",
        "algorithm": "d R' U' R d' R U R'"
    },
    {
        "id": "f2l-37",
        "name": "F2L 37",
        "algorithm": "R U R' U' R U2 R' U' R U R'"
    },
    {
        "id": "f2l-38",
        "name": "F2L 38",
        "algorithm": "R U R' U' R U R' U2 R U' R'"
    },
    {
        "id": "f2l-39",
        "name": "F2L 39",
        "algorithm": "R U R' U2 R U' R' U R U R'"
    },
    {
        "id": "f2l-40",
        "name": "F2L 40",
        "algorithm": "R U' R' U R U2 R' U R U' R'"
    },
    {
        "id": "f2l-41",
        "name": "F2L 41",
        "algorithm": "R U' R' U y' R' U R U' R' U R"
    }
],
  OLL: [
    {
        "id": "oll-01",
        "name": "OLL 01",
        "algorithm": "R U2 R2 F R F' U2 R' F R F'"
    },
    {
        "id": "oll-02",
        "name": "OLL 02",
        "algorithm": "F R U R' U' F' f R U R' U' f'"
    },
    {
        "id": "oll-03",
        "name": "OLL 03",
        "algorithm": "f R U R' U' f' U' F R U R' U' F'"
    },
    {
        "id": "oll-04",
        "name": "OLL 04",
        "algorithm": "f R U R' U' f' U F R U R' U' F'"
    },
    {
        "id": "oll-05",
        "name": "OLL 05",
        "algorithm": "r' U2 R U R' U r"
    },
    {
        "id": "oll-06",
        "name": "OLL 06",
        "algorithm": "r U2 R' U' R U' r'"
    },
    {
        "id": "oll-07",
        "name": "OLL 07",
        "algorithm": "r U R' U R U2 r'"
    },
    {
        "id": "oll-08",
        "name": "OLL 08",
        "algorithm": "r' U' R U' R' U2 r"
    },
    {
        "id": "oll-09",
        "name": "OLL 09",
        "algorithm": "R U R' U' R' F R2 U R' U' F'"
    },
    {
        "id": "oll-10",
        "name": "OLL 10",
        "algorithm": "R U R' U R' F R F' R U2 R'"
    },
    {
        "id": "oll-11",
        "name": "OLL 11",
        "algorithm": "r U R' U R' F R F' R U2 r'"
    },
    {
        "id": "oll-12",
        "name": "OLL 12",
        "algorithm": "M' R' U' R U' R' U2 R U' R r'"
    },
    {
        "id": "oll-13",
        "name": "OLL 13",
        "algorithm": "F U R U' R2 F' R U R U' R'"
    },
    {
        "id": "oll-14",
        "name": "OLL 14",
        "algorithm": "R' F R U R' F' R F U' F'"
    },
    {
        "id": "oll-15",
        "name": "OLL 15",
        "algorithm": "l' U' l L' U' L U l' U l"
    },
    {
        "id": "oll-16",
        "name": "OLL 16",
        "algorithm": "r U r' R U R' U' r U' r'"
    },
    {
        "id": "oll-17",
        "name": "OLL 17",
        "algorithm": "F R' F' R2 r' U R U' R' U' M'"
    },
    {
        "id": "oll-18",
        "name": "OLL 18",
        "algorithm": "r U R' U R U2 r2 U' R U' R' U2 r"
    },
    {
        "id": "oll-19",
        "name": "OLL 19",
        "algorithm": "r' R U R U R' U' M' R' F R F'"
    },
    {
        "id": "oll-20",
        "name": "OLL 20",
        "algorithm": "r U R' U' M2 U R U' R' U' M'"
    },
    {
        "id": "oll-21",
        "name": "OLL 21",
        "algorithm": "R U2 R' U' R U R' U' R U' R'"
    },
    {
        "id": "oll-22",
        "name": "OLL 22",
        "algorithm": "R U2 R2 U' R2 U' R2 U2 R"
    },
    {
        "id": "oll-23",
        "name": "OLL 23",
        "algorithm": "R2 D' R U2 R' D R U2 R"
    },
    {
        "id": "oll-24",
        "name": "OLL 24",
        "algorithm": "r U R' U' r' R U R U' R'"
    },
    {
        "id": "oll-25",
        "name": "OLL 25",
        "algorithm": "F' r U R' U' r' F R"
    },
    {
        "id": "oll-26",
        "name": "OLL 26",
        "algorithm": "R U2 R' U' R U' R'"
    },
    {
        "id": "oll-27",
        "name": "OLL 27",
        "algorithm": "R U R' U R U2 R'"
    },
    {
        "id": "oll-28",
        "name": "OLL 28",
        "algorithm": "r U R' U' r' R U R U' R'"
    },
    {
        "id": "oll-29",
        "name": "OLL 29",
        "algorithm": "R U R' U' R U' R' F' U' F R U R'"
    },
    {
        "id": "oll-30",
        "name": "OLL 30",
        "algorithm": "F R' F R2 U' R' U' R U R' F2"
    },
    {
        "id": "oll-31",
        "name": "OLL 31",
        "algorithm": "R' U' F U R U' R' F' R"
    },
    {
        "id": "oll-32",
        "name": "OLL 32",
        "algorithm": "L U F' U' L' U L F L'"
    },
    {
        "id": "oll-33",
        "name": "OLL 33",
        "algorithm": "R U R' U' R' F R F'"
    },
    {
        "id": "oll-34",
        "name": "OLL 34",
        "algorithm": "R U R2 U' R' F R U R U' F'"
    },
    {
        "id": "oll-35",
        "name": "OLL 35",
        "algorithm": "R U2 R2 F R F' R U2 R'"
    },
    {
        "id": "oll-36",
        "name": "OLL 36",
        "algorithm": "L' U' L U' L' U L U L F' L' F"
    },
    {
        "id": "oll-37",
        "name": "OLL 37",
        "algorithm": "F R' F' R U R U' R'"
    },
    {
        "id": "oll-38",
        "name": "OLL 38",
        "algorithm": "R U R' U R U' R' U' R' F R F'"
    },
    {
        "id": "oll-39",
        "name": "OLL 39",
        "algorithm": "L F' L' U' L U F U' L'"
    },
    {
        "id": "oll-40",
        "name": "OLL 40",
        "algorithm": "R' F R U R' U' F' U R"
    },
    {
        "id": "oll-41",
        "name": "OLL 41",
        "algorithm": "R U R' U R U2 R' F R U R' U' F'"
    },
    {
        "id": "oll-42",
        "name": "OLL 42",
        "algorithm": "R' U' R U' R' U2 R F R U R' U' F'"
    },
    {
        "id": "oll-43",
        "name": "OLL 43",
        "algorithm": "F' U' L' U L F"
    },
    {
        "id": "oll-44",
        "name": "OLL 44",
        "algorithm": "F R U R' U' F'"
    },
    {
        "id": "oll-45",
        "name": "OLL 45",
        "algorithm": "F R U R' U' F'"
    },
    {
        "id": "oll-46",
        "name": "OLL 46",
        "algorithm": "R' U' R' F R F' U R"
    },
    {
        "id": "oll-47",
        "name": "OLL 47",
        "algorithm": "R' U' R' F R F' U R"
    },
    {
        "id": "oll-48",
        "name": "OLL 48",
        "algorithm": "F R U R' U' R U R' U' F'"
    },
    {
        "id": "oll-49",
        "name": "OLL 49",
        "algorithm": "r U' r2 U r2 U r2 U' r"
    },
    {
        "id": "oll-50",
        "name": "OLL 50",
        "algorithm": "r' U r2 U' r2 U' r2 U r'"
    },
    {
        "id": "oll-51",
        "name": "OLL 51",
        "algorithm": "F U R U' R' U R U' R' F'"
    },
    {
        "id": "oll-52",
        "name": "OLL 52",
        "algorithm": "R U R' U R d' R U' R' F'"
    },
    {
        "id": "oll-53",
        "name": "OLL 53",
        "algorithm": "r' U' R U' R' U R U' R' U2 r"
    },
    {
        "id": "oll-54",
        "name": "OLL 54",
        "algorithm": "r U R' U R U' R' U R U2 r'"
    },
    {
        "id": "oll-55",
        "name": "OLL 55",
        "algorithm": "R U2 R2 U' R U' R' U2 F R F'"
    },
    {
        "id": "oll-56",
        "name": "OLL 56",
        "algorithm": "F R U R' U' R F' r U R' U' r'"
    },
    {
        "id": "oll-57",
        "name": "OLL 57",
        "algorithm": "R U R' U' M' U R U' r'"
    }
],
  PLL: [
    {
        "id": "pll-aa",
        "name": "Aa Perm",
        "algorithm": "x R' U R' D2 R U' R' D2 R2 x'"
    },
    {
        "id": "pll-ab",
        "name": "Ab Perm",
        "algorithm": "x R2 D2 R U R' D2 R U' R x'"
    },
    {
        "id": "pll-e",
        "name": "E Perm",
        "algorithm": "x' R U' R' D R U R' D' R U R' D R U' R' D' x"
    },
    {
        "id": "pll-f",
        "name": "F Perm",
        "algorithm": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"
    },
    {
        "id": "pll-ga",
        "name": "Ga Perm",
        "algorithm": "R2 u R' U R' U' R u' R2 y' R' U R"
    },
    {
        "id": "pll-gb",
        "name": "Gb Perm",
        "algorithm": "F' U' F R2 u R' U R U' R u' R2"
    },
    {
        "id": "pll-gc",
        "name": "Gc Perm",
        "algorithm": "R2 u' R U' R U R' u R2 y R U' R'"
    },
    {
        "id": "pll-gd",
        "name": "Gd Perm",
        "algorithm": "R U R' y' R2 u' R U' R' U R' u R2"
    },
    {
        "id": "pll-h",
        "name": "H Perm",
        "algorithm": "M2 U M2 U2 M2 U M2"
    },
    {
        "id": "pll-ja",
        "name": "Ja Perm",
        "algorithm": "x R2 F R F' R U2 r' U r U2 x'"
    },
    {
        "id": "pll-jb",
        "name": "Jb Perm",
        "algorithm": "R U R' F' R U R' U' R' F R2 U' R' U'"
    },
    {
        "id": "pll-na",
        "name": "Na Perm",
        "algorithm": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"
    },
    {
        "id": "pll-nb",
        "name": "Nb Perm",
        "algorithm": "r' D' F r U' r' F' D r2 U r' U' r' F r F'"
    },
    {
        "id": "pll-ra",
        "name": "Ra Perm",
        "algorithm": "R U R' F' R U2 R' U2 R' F R U R U2 R'"
    },
    {
        "id": "pll-rb",
        "name": "Rb Perm",
        "algorithm": "R' U2 R U2 R' F R U R' U' R' F' R2"
    },
    {
        "id": "pll-t",
        "name": "T Perm",
        "algorithm": "R U R' U' R' F R2 U' R' U' R U R' F'"
    },
    {
        "id": "pll-ua",
        "name": "Ua Perm",
        "algorithm": "R U' R U R U R U' R' U' R2"
    },
    {
        "id": "pll-ub",
        "name": "Ub Perm",
        "algorithm": "R2 U R U R' U' R' U' R' U R'"
    },
    {
        "id": "pll-v",
        "name": "V Perm",
        "algorithm": "R' U R' d' R' F' R2 U' R' U R' F R F"
    },
    {
        "id": "pll-y",
        "name": "Y Perm",
        "algorithm": "F R U' R' U' R U R' F' R U R' U' R' F R F'"
    },
    {
        "id": "pll-z",
        "name": "Z Perm",
        "algorithm": "M2 U M2 U M' U2 M2 U2 M'"
    }
]
};
